=== 42core-team/monorepo/server/data/json-schemas/configs/server-config.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "ServerConfig",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"replayFolderPaths",
		"timeoutTicks",
		"timeoutMs",
		"clientWaitTimeoutMs",
		"clientConnectTimeoutMs",
		"clientPacketsMaxSizeKb"
	],
	"properties": {
		"replayFolderPaths": {
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "string",
				"minLength": 1
			}
		},
		"timeoutTicks": {
			"type": "integer",
			"minimum": 1
		},
		"timeoutMs": {
			"type": "integer",
			"minimum": 1
		},
		"clientWaitTimeoutMs": {
			"type": "integer",
			"minimum": 1
		},
		"clientConnectTimeoutMs": {
			"type": "integer",
			"minimum": 1
		},
		"clientPacketsMaxSizeKb": {
			"type": "integer",
			"minimum": 1
		}
	}
}

=== 42core-team/monorepo/bots/configs/fake_demo/server.config.json
{
    "replayFolderPaths": [
        "/workspace/replays",
        "/workspaces/monorepo",
        "/workspaces/monorepo/visualizer/public/replays",
        "./replays"
    ],
    "timeoutTicks": 30000,
    "timeoutMs": 3000000,
    "clientWaitTimeoutMs": 30000,
    "clientConnectTimeoutMs": 30000,
    "clientPacketsMaxSizeKb": 16
}
