=== 42core-team/monorepo/server/data/config-schemas/game-config.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "GameConfig",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"gridSize",
		"idleIncome",
		"idleIncomeTimeOut",
		"depositHp",
		"depositIncome",
		"gemPileIncome",
		"coreHp",
		"coreSpawnCooldown",
		"initialBalance",
		"wallHp",
		"wallBuildCost",
		"bombHp",
		"bombCountdown",
		"bombThrowCost",
		"bombReach",
		"bombDamageCore",
		"bombDamageUnit",
		"bombDamageDeposit",
		"worldGenerator",
		"worldGeneratorConfig",
		"units",
		"corePositions"
	],
	"properties": {
		"gridSize": {
			"type": "integer",
			"minimum": 2,
			"maximum": 200
		},
		"seed": {
			"type": "string"
		},
		"idleIncome": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"idleIncomeTimeOut": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"depositHp": {
			"type": "integer",
			"minimum": 1,
			"maximum": 10000000
		},
		"depositIncome": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"gemPileIncome": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"coreHp": {
			"type": "integer",
			"minimum": 1,
			"maximum": 10000000
		},
		"coreSpawnCooldown": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"initialBalance": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"wallHp": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"wallBuildCost": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"bombHp": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"bombCountdown": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"bombThrowCost": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"bombReach": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"bombDamageCore": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"bombDamageUnit": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"bombDamageDeposit": {
			"type": "integer",
			"minimum": 0,
			"maximum": 10000000
		},
		"worldGenerator": {
			"type": "string",
			"enum": [
				"jigsaw",
				"sparse",
				"hardcoded",
				"empty"
			]
		},
		"worldGeneratorConfig": {
			"type": "object"
		},
		"units": {
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "#/$defs/unit"
			}
		},
		"corePositions": {
			"type": "array",
			"minItems": 2,
			"items": {
				"$ref": "#/$defs/position"
			}
		}
	},
	"allOf": [
		{
			"if": {
				"properties": {
					"worldGenerator": {
						"const": "jigsaw"
					}
				},
				"required": [
					"worldGenerator"
				]
			},
			"then": {
				"properties": {
					"worldGeneratorConfig": {
						"$ref": "#/$defs/jigsawCfg"
					}
				}
			}
		},
		{
			"if": {
				"properties": {
					"worldGenerator": {
						"const": "sparse"
					}
				},
				"required": [
					"worldGenerator"
				]
			},
			"then": {
				"properties": {
					"worldGeneratorConfig": {
						"$ref": "#/$defs/sparseCfg"
					}
				}
			}
		},
		{
			"if": {
				"properties": {
					"worldGenerator": {
						"const": "hardcoded"
					}
				},
				"required": [
					"worldGenerator"
				]
			},
			"then": {
				"properties": {
					"worldGeneratorConfig": {
						"$ref": "#/$defs/hardcodedCfg"
					}
				}
			}
		},
		{
			"if": {
				"properties": {
					"worldGenerator": {
						"const": "empty"
					}
				},
				"required": [
					"worldGenerator"
				]
			},
			"then": {
				"properties": {
					"worldGeneratorConfig": {
						"$ref": "#/$defs/emptyCfg"
					}
				}
			}
		}
	],
	"$defs": {
		"position": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"x",
				"y"
			],
			"properties": {
				"x": {
					"type": "integer",
					"minimum": 0,
					"maximum": 100000
				},
				"y": {
					"type": "integer",
					"minimum": 0,
					"maximum": 100000
				}
			}
		},
		"unit": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"name",
				"visualizer_asset_path",
				"cost",
				"hp",
				"baseActionCooldown",
				"maxActionCooldown",
				"balancePerCooldownStep",
				"damageCore",
				"damageUnit",
				"damageDeposit",
				"damageWall",
				"damageBomb",
				"buildType"
			],
			"properties": {
				"name": {
					"type": "string",
					"minLength": 1
				},
				"visualizer_asset_path": {
					"type": "string",
					"minLength": 1
				},
				"cost": {
					"type": "integer",
					"minimum": 0
				},
				"hp": {
					"type": "integer",
					"minimum": 0
				},
				"baseActionCooldown": {
					"type": "integer",
					"minimum": 0
				},
				"maxActionCooldown": {
					"type": "integer",
					"minimum": 0
				},
				"balancePerCooldownStep": {
					"type": "integer",
					"minimum": 1
				},
				"damageCore": {
					"type": "integer",
					"minimum": 0
				},
				"damageUnit": {
					"type": "integer",
					"minimum": 0
				},
				"damageDeposit": {
					"type": "integer",
					"minimum": 0
				},
				"damageWall": {
					"type": "integer",
					"minimum": 0
				},
				"damageBomb": {
					"type": "integer",
					"minimum": 0
				},
				"buildType": {
					"type": "string",
					"enum": [
						"none",
						"wall",
						"bomb"
					]
				}
			}
		},
		"jigsawCfg": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"templatePlaceAttemptCount",
				"additionalWallPlaceAttemptCount",
				"depositCount",
				"gemPileCount",
				"minTemplateSpacing",
				"minCoreDistance",
				"depositAdditionalIncomePerAdjacentWall",
				"depositMultiplierIfFullySurrounded",
				"randomDepositIncomeVariation",
				"randomGemPileIncomeVariation"
			],
			"properties": {
				"templatePlaceAttemptCount": {
					"type": "integer",
					"minimum": 0,
					"maximum": 10000000
				},
				"additionalWallPlaceAttemptCount": {
					"type": "integer",
					"minimum": 0,
					"maximum": 10000000
				},
				"depositCount": {
					"type": "integer",
					"minimum": 0,
					"maximum": 100000
				},
				"gemPileCount": {
					"type": "integer",
					"minimum": 0,
					"maximum": 100000
				},
				"minTemplateSpacing": {
					"type": "integer",
					"minimum": 0,
					"maximum": 1000
				},
				"minCoreDistance": {
					"type": "integer",
					"minimum": 0,
					"maximum": 1000
				},
				"depositAdditionalIncomePerAdjacentWall": {
					"type": "integer",
					"minimum": 0,
					"maximum": 10000000
				},
				"depositMultiplierIfFullySurrounded": {
					"type": "number",
					"minimum": 0,
					"maximum": 1000
				},
				"randomDepositIncomeVariation": {
					"type": "integer",
					"minimum": 0,
					"maximum": 10000000
				},
				"randomGemPileIncomeVariation": {
					"type": "integer",
					"minimum": 0,
					"maximum": 10000000
				}
			}
		},
		"sparseCfg": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"depositCount",
				"depositBalanceVariation",
				"gemPileCount",
				"gemPileBalanceVariation",
				"wallCount",
				"coreBuffer"
			],
			"properties": {
				"depositCount": {
					"type": "integer",
					"minimum": 0,
					"maximum": 100000
				},
				"depositBalanceVariation": {
					"type": "integer",
					"minimum": 0,
					"maximum": 10000000
				},
				"gemPileCount": {
					"type": "integer",
					"minimum": 0,
					"maximum": 100000
				},
				"gemPileBalanceVariation": {
					"type": "integer",
					"minimum": 0,
					"maximum": 10000000
				},
				"wallCount": {
					"type": "integer",
					"minimum": 0,
					"maximum": 1000000
				},
				"coreBuffer": {
					"type": "integer",
					"minimum": 0,
					"maximum": 1000
				}
			}
		},
		"hardcodedCfg": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"map"
			],
			"properties": {
				"map": {
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "string",
						"minLength": 1
					}
				}
			}
		},
		"emptyCfg": {
			"type": "object",
			"additionalProperties": false,
			"maxProperties": 0
		}
	}
}

=== 42core-team/monorepo/bots/hardcore/configs/soft-config.json
{
	"gridSize": 20,
	"seed": "",
	"idleIncome": 1,
	"idleIncomeTimeOut": 1000,
	"depositHp": 50,
	"depositIncome": 200,
	"gemPileIncome": 75,
	"coreHp": 200,
	"coreSpawnCooldown": 30,
	"initialBalance": 100,
	"wallHp": 50,
	"wallBuildCost": 20,
	"bombHp": 25,
	"bombCountdown": 10,
	"bombThrowCost": 50,
	"bombReach": 3,
	"bombDamageCore": 50,
	"bombDamageUnit": 30,
	"bombDamageDeposit": 40,
	"worldGenerator": "sparse",
	"worldGeneratorConfig": {
		"depositCount": 20,
		"depositBalanceVariation": 100,
		"gemPileCount": 10,
		"gemPileBalanceVariation": 50,
		"wallCount": 30,
		"coreBuffer": 3
	},
	"units": [
		{
			"name": "Warrior",
			"visualizer_asset_path": "warrior",
			"cost": 150,
			"hp": 35,
			"baseActionCooldown": 5,
			"maxActionCooldown": 20,
			"balancePerCooldownStep": 30,
			"damageCore": 12,
			"damageUnit": 6,
			"damageDeposit": 4,
			"damageWall": 5,
			"damageBomb": 5,
			"buildType": "none"
		},
		{
			"name": "Miner",
			"visualizer_asset_path": "miner",
			"cost": 100,
			"hp": 20,
			"baseActionCooldown": 5,
			"maxActionCooldown": 10,
			"balancePerCooldownStep": 100,
			"damageCore": 5,
			"damageUnit": 2,
			"damageDeposit": 10,
			"damageWall": 12,
			"damageBomb": 5,
			"buildType": "none"
		},
		{
			"name": "Carrier",
			"visualizer_asset_path": "carrier",
			"cost": 200,
			"hp": 10,
			"baseActionCooldown": 0,
			"maxActionCooldown": 1,
			"balancePerCooldownStep": 500,
			"damageCore": 0,
			"damageUnit": 0,
			"damageDeposit": 0,
			"damageWall": 3,
			"damageBomb": 5,
			"buildType": "none"
		}
	],
	"corePositions": [
		{
			"x": 0,
			"y": 0
		},
		{
			"x": 19,
			"y": 19
		}
	]
}
